app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => 'guest'], function () {
    get('/login', ['as' => 'show_login', function () {
        return view('login');
    }]);

    post('/login', ['as' => 'post_login', 'uses' => 'AuthController@authenticate']);
});

Route::group(['middleware' => 'auth'], function () {
    get('/', ['as' => 'profile', 'uses' => 'AuthController@show']);
    get('/admin', ['as' => 'admin', 'uses' => 'AuthController@admin']);

    post('/grade', ['as' => 'add_grade', 'uses' => 'GradeController@store']);

    post('/project', ['as' => 'add_project', 'uses' => 'ProjectController@store']);
    delete('/project', ['as' => 'delete_project', 'uses' => 'ProjectController@delete']);
    get('/project/{id}', ['as' => 'download_project', 'uses' => 'ProjectController@download']);

    get('logout', ['as' => 'logout', function () {
        Auth::logout();
        return redirect()->route('show_login');
    }]);
});

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract {
    use Authenticatable, Authorizable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['remember_token'];

    public function Project()
    {
        return $this->hasMany(Project::class);
    }

    public function Grade()
    {
        return $this->hasMany(Grade::class);
    }

    public function getMediaAttribute(){
        $sum = 0;
        $projects = $this->Project;
        if($projects->count() < config('settings.max_project_upload')){
            return null;
        }
        foreach($projects as $project){
            $media_proj = $project->Media;
            if(is_null($media_proj)){
                return null;
            }
            $sum += $project->Media;
        }
        return round($sum / $projects->count(), 2);
    }
}

resources/views/include/add_project.blade.php
<div class="panel panel-primary">
    @if(! is_null($warning_message))
        <div class="panel-heading">
            <p class="panel-title">{{$warning_message}}</p>
        </div>
    @endif
    @if($user->Project->count() < config('settings.max_project_upload'))
        <div class="panel-body">
            <form class="form-inline" method="post" action="{{route('add_project')}}" enctype="multipart/form-data">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <input class="form-control" id="name" type="text" name="name" placeholder="Project name"
                       required>
                <input class="form-control" type="file" name="upload"
                       accept="file_extension|.pdf,.doc,.docx,.txt,.rtf,.ppt" required>
                <button class="btn btn-primary" type="submit">Upload project</button>
            </form>
        </div>
    @endif
</div>

resources/views/include/grade.blade.php
@for($i = 0; $i < config('settings.grade_for_project'); $i++)
    <td class="text-center">
        @if($project->Grade->count() > $i)
            {{ $project->Grade[$i]->grade }}
        @endif
    </td>
@endfor
<td class="text-center">
    {{$project->media}}
</td>

resources/views/include/notification.blade.php
@foreach ($errors->all() as $error)
    <p class="alert alert-danger alert-custom text-center">{{ $error }}</p>
@endforeach

@if(Session::has('notification'))
    <p class="alert alert-info alert-custom text-center">{{Session::get('notification')}}</p>
@endif